### ISSUE TITLE
Root routes not being handled

### ISSUE THREAD

**Issue by lemonsrc** [MetisMachine/pilot#7]
Routes defined at the root level of any router are not being handled.

For example, the following router will not return a response body when making requests on "/":
```
defmodule Example.Router do
  use Pilot.Router

  get "/" do
    "Hello, world!"
  end
end
```

The following error occurs in `iex`
```
15:17:54.566 [error] #PID<0.339.0> running Example.Router terminated
Server: localhost:8080 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
        (plug) lib/plug/adapters/cowboy/handler.ex:42: Plug.Adapters.Cowboy.Handler.maybe_send/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/wes/Workspace/pilot/example/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by lemonsrc** [comment]
Closed by PR #10
